# Generated by Django 6.1 on 2026-08-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_picture',
            field=models.TextField(blank=True, help_text='Base64 encoded string or URL for cover image', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.TextField(blank=True, help_text='Base64 encoded string or URL for avatar', null=True),
        ),
    ]
