# Generated by Django 6.1 on 2026-08-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_background_picture_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biceps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Biceps size in inches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='body_fat',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body fat percentage', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calves',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calves size in inches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chest size in inches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thighs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Thighs size in inches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Waist size in inches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body weight in preferred unit', max_digits=5, null=True),
        ),
    ]
